---
title: "مثال ۱۱-۱: مجموعهٔ نمونه (معرفی  `data.frame`)"
author: "رامین مجاب"
output: md_document
---

**(صفحهٔ ۳۰۸ کتاب)**

قالب اصلی ذخیره‌سازی و استفاده از مجموعهٔ مشاهدات در **R**، `data.frame` است. در کاربردهای معمول،  این شیء، اشیاء دیگر را در یک ساختار مستطیلی ذخیره می‌کند. از این نظر، شبیه به `matrix` اما بسیار منعطف‌تر است. کد زیر را ملاحظه کنید:
```{r}
D <- datasets::mtcars
class(datasets::mtcars)
head(D, 4)
```
در اینجا، یک مجموعهٔ داده را از بستهٔ نرم‌افزاری `datasets` فراخوانی کرده‌ایم. همان‌طور که ملاحظه می‌شود، کلاس این مجموعه `data.frame` است. تابع `head()` چند سطر ابتدایی را استخراج می‌کند. به ساختار مستطیلی گزارش‌شده توجه کنید. چند نکتهٔ زیر را نیز ملاحظه کنید:

- به نصب   بستهٔ `datasets` نیازی نیست. این ازجملهٔ بسته‌هایی است که به‌صورت پیش‌فرض در **R** نصب شده است. در این بسته، مجموعه داده‌های زیادی وجود دارد. در این مثال، از مجموعهٔ `mtcars` استفاده کرده‌ایم.
- همان‌طور که بیان شد، تابع `head()` چند سطر ابتدایی را می‌گیرد. تابعی مشابه با نام `tail` برای استخراج سطرهای انتهایی وجود دارد. اگر به ساختار ارزش‌های گزارش‌شده توجه کنید و آن را با بحث متن منطبق کنید، مشخص می‌شود که سطرهای `data.frame` حاوی مشاهدات و ستون‌های آن حاوی متغیرهاست. پس، ارزش گزارش‌شده در سطر $i$ و ستون $j$، ویژگی $j$ام در مشاهدهٔ $i$ام است.  
- مجموعهٔ `mtcars` دارای `r nrow(datasets::mtcars)` سطر و `r ncol(datasets::mtcars)` ستون است. پس، این مجموعه دارای `r nrow(datasets::mtcars)` مشاهده است. هر مشاهده،  مصرف بنزین و `r ncol(datasets::mtcars)-1` ویژگی دیگر ماشین (نظیر «مسافت به مایل با یک گالن»، «تعداد سیلندر»، «وزن»، و غیره)‌ را شامل می‌شود (این ارزش‌ها از مجلهٔ <span dir="ltr">Motor Trend</span>  در سال ۱۹۷۴ گزارش شده است).

مهم‌ترین تفاوت  `data.frame` و  `matrix` آن است که  هر ستون در `data.frame` می‌تواند نوع متفاوتی از اطلاعات را داشته باشد. همچنین، این کلاس ساختار مناسب‌تری برای ذخیرهٔ داده‌های طبقه‌ای (<span dir="ltr">categorical data</span>) دارد.  
البته از منظر نظریهٔ ماتریس،  نمایش مستطیلی ماتریس کافی است و چنین ویژگی‌هایی اهمیت ندارد. به‌عبارت دیگر، به ماتریس ضرایب در یک دستگاه معادلات خطی (تعریف ۹-۱، صفحهٔ ۲۷۸ در کتاب) توجه کنید. در بسیاری از کاربردها، سطرهای ماتریس را مشاهدات و ستون‌های آن را متغیرها تفسیر خواهیم کرد (مثلاً، نگاه کنید به: فصل ۱۳، صفحهٔ ۳۴۳ کتاب).‌


